
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB9wo-PfqydI0p02iNavgGskZyc8BtcZHs",
      authDomain: "translation-flutter-mobil.firebaseapp.com",
      projectId: "translation-flutter-mobil",
      storageBucket: "translation-flutter-mobil.appspot.com",
      messagingSenderId: "904810739759",
      appId: "1:904810739759:web:0befc9bc245eebb897eeda",
      //measurementId: 'G-D5JK51JKFX',
      databaseURL:
          "https://translation-flutter-mobil-default-rtdb.europe-west1.firebasedatabase.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
            apiKey: "AIzaSyBnkMBQ-V6mMQfmMhXplU6BtUPYvNYqqNY",
            authDomain: "translation-flutter-mobil.firebaseapp.com",
            projectId: "translation-flutter-mobil",
            storageBucket: "translation-flutter-mobil.appspot.com",
            messagingSenderId: "904810739759",
            databaseURL:
                "https://translation-flutter-mobil-default-rtdb.europe-west1.firebasedatabase.app",
            appId: "1:904810739759:android:0ae88fcaa10aa62d97eeda"
  );
}
